-- Kuwait Chef / ELAMIGOS inventory migration
-- Source of truth for the new PostgreSQL model; derived from legacy Apps Script HDRS.

create extension if not exists pgcrypto;

create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type text,
  address text,
  is_active boolean not null default true,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  parent_id bigint references public.branches(id),
  loc_type text,
  manager text,
  is_stock_location boolean not null default true,
  sort_order integer
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  parent_id bigint references public.categories(id),
  icon text,
  storage_type text,
  count_freq text
);

create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  is_active boolean not null default true,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.units (
  code text primary key,
  name text not null,
  kind text not null,
  base_code text not null,
  factor numeric(18,6) not null default 1,
  decimals integer not null default 0,
  is_deleted boolean not null default false
);

create table if not exists public.items (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id),
  name text not null,
  unit text,
  unit_cost numeric(18,6) not null default 0,
  item_type text,
  min_stock numeric(18,6) not null default 0,
  is_active boolean not null default true,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  item_code text unique,
  base_unit text,
  stock_unit text,
  purchase_unit text,
  issue_unit text,
  pack_qty numeric(18,6),
  photo_url text,
  storage_type text,
  shelf_life_days integer,
  yield_pct numeric(8,3) default 100,
  barcode text,
  preferred_vendor_id bigint references public.vendors(id),
  is_sellable boolean not null default false,
  is_recipe_item boolean not null default false
);

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  grn_no text unique,
  vendor_id bigint references public.vendors(id),
  branch_id bigint references public.branches(id),
  vendor_invoice_no text,
  purchase_date date,
  total_amount numeric(18,6) not null default 0,
  status text,
  received_by uuid,
  notes text,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.purchase_items (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.purchases(id) on delete cascade,
  item_id bigint not null references public.items(id),
  qty numeric(18,6) not null,
  unit_cost numeric(18,6) not null default 0,
  amount numeric(18,6) not null default 0
);

create table if not exists public.purchase_requests (
  id bigint generated by default as identity primary key,
  request_no text unique,
  branch_id bigint references public.branches(id),
  to_branch_id bigint references public.branches(id),
  request_date date,
  required_date date,
  status text,
  requested_by uuid,
  approved_by uuid,
  notes text,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  priority text,
  meal_period text,
  covers numeric(18,3),
  approved_at timestamptz,
  reject_reason text
);

create table if not exists public.purchase_request_items (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.purchase_requests(id) on delete cascade,
  item_id bigint not null references public.items(id),
  requested_qty numeric(18,6) not null default 0,
  approved_qty numeric(18,6) not null default 0,
  dispatched_qty numeric(18,6) not null default 0,
  unit_cost numeric(18,6) not null default 0,
  amount numeric(18,6) not null default 0,
  line_note text,
  short_reason text
);

create table if not exists public.productions (
  id bigint generated by default as identity primary key,
  production_no text unique,
  branch_id bigint references public.branches(id),
  item_id bigint references public.items(id),
  output_qty numeric(18,6) not null default 0,
  production_date date,
  status text,
  produced_by uuid,
  unit_cost numeric(18,6) not null default 0,
  notes text,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.production_materials (
  id bigint generated by default as identity primary key,
  production_id bigint not null references public.productions(id) on delete cascade,
  item_id bigint not null references public.items(id),
  qty_used numeric(18,6) not null default 0,
  unit_cost numeric(18,6) not null default 0,
  amount numeric(18,6) not null default 0
);

create table if not exists public.dispatches (
  id bigint generated by default as identity primary key,
  invoice_no text unique,
  request_id bigint references public.purchase_requests(id),
  from_branch_id bigint references public.branches(id),
  to_branch_id bigint references public.branches(id),
  dispatch_date date,
  total_amount numeric(18,6) not null default 0,
  status text,
  dispatched_by uuid,
  received_by uuid,
  received_at timestamptz,
  notes text,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dispatch_items (
  id bigint generated by default as identity primary key,
  dispatch_id bigint not null references public.dispatches(id) on delete cascade,
  item_id bigint not null references public.items(id),
  qty numeric(18,6) not null default 0,
  unit_cost numeric(18,6) not null default 0,
  amount numeric(18,6) not null default 0
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  item_id bigint not null references public.items(id),
  qty numeric(18,6) not null default 0,
  updated_at timestamptz not null default now(),
  unique(branch_id,item_id)
);

create table if not exists public.stock_ledger (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  item_id bigint not null references public.items(id),
  movement_type text not null,
  reference_id bigint,
  qty_in numeric(18,6) not null default 0,
  qty_out numeric(18,6) not null default 0,
  balance numeric(18,6) not null default 0,
  movement_date timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.stock_adjustments (
  id bigint generated by default as identity primary key,
  adjustment_no text unique,
  branch_id bigint references public.branches(id),
  item_id bigint references public.items(id),
  adjustment_type text,
  qty numeric(18,6) not null default 0,
  reason text,
  adjustment_date date,
  adjusted_by uuid,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reason_code text,
  shift text,
  photo_url text,
  approved_by uuid,
  approved_at timestamptz,
  entry_unit text,
  entry_qty numeric(18,6),
  batch_id bigint
);

create table if not exists public.par_levels (
  id bigint generated by default as identity primary key,
  branch_id bigint references public.branches(id),
  item_id bigint references public.items(id),
  min_qty numeric(18,6) not null default 0,
  max_qty numeric(18,6) not null default 0,
  reorder_qty numeric(18,6) not null default 0,
  is_deleted boolean not null default false,
  updated_at timestamptz not null default now(),
  unique(branch_id,item_id)
);

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  item_id bigint references public.items(id),
  name text not null,
  yield_qty numeric(18,6),
  yield_unit text,
  portion_size numeric(18,6),
  notes text,
  is_active boolean not null default true,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recipe_lines (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  item_id bigint not null references public.items(id),
  qty numeric(18,6) not null default 0,
  unit text,
  waste_pct numeric(8,3) not null default 0
);

create table if not exists public.consumption (
  id bigint generated by default as identity primary key,
  consumption_no text unique,
  branch_id bigint references public.branches(id),
  date date,
  shift text,
  source text,
  ref_id bigint,
  total_cost numeric(18,6) not null default 0,
  recorded_by uuid,
  notes text,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.consumption_lines (
  id bigint generated by default as identity primary key,
  consumption_id bigint not null references public.consumption(id) on delete cascade,
  item_id bigint not null references public.items(id),
  qty numeric(18,6) not null default 0,
  unit_cost numeric(18,6) not null default 0,
  amount numeric(18,6) not null default 0
);

create table if not exists public.stock_counts (
  id bigint generated by default as identity primary key,
  count_no text unique,
  branch_id bigint references public.branches(id),
  category_id bigint references public.categories(id),
  status text,
  blind boolean not null default false,
  started_at timestamptz,
  closed_at timestamptz,
  counted_by uuid,
  approved_by uuid,
  variance_value numeric(18,6) not null default 0,
  notes text,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stock_count_lines (
  id bigint generated by default as identity primary key,
  count_id bigint not null references public.stock_counts(id) on delete cascade,
  item_id bigint not null references public.items(id),
  system_qty numeric(18,6) not null default 0,
  counted_qty numeric(18,6),
  variance numeric(18,6),
  variance_value numeric(18,6),
  note text,
  is_counted boolean not null default false
);

create table if not exists public.batches (
  id bigint generated by default as identity primary key,
  batch_no text,
  item_id bigint references public.items(id),
  branch_id bigint references public.branches(id),
  source text,
  ref_id bigint,
  received_date date,
  expiry_date date,
  qty_in numeric(18,6) not null default 0,
  qty_remaining numeric(18,6) not null default 0,
  status text,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.vendor_items (
  id bigint generated by default as identity primary key,
  vendor_id bigint references public.vendors(id),
  item_id bigint references public.items(id),
  vendor_code text,
  price numeric(18,6) not null default 0,
  pack_unit text,
  pack_qty numeric(18,6),
  lead_days integer,
  min_order numeric(18,6),
  last_date date,
  is_deleted boolean not null default false,
  updated_at timestamptz not null default now(),
  unique(vendor_id,item_id)
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid,
  username text,
  action text not null,
  details text
);

-- Legacy role/page matrix is represented separately from auth users.
create table if not exists public.roles (
  key text primary key,
  label text not null,
  color text,
  sort_order integer not null default 0,
  is_super boolean not null default false,
  hidden_signup boolean not null default false
);

create table if not exists public.role_permissions (
  role_key text not null references public.roles(key) on delete cascade,
  page_key text not null,
  can_view boolean not null default false,
  can_add boolean not null default false,
  can_edit boolean not null default false,
  can_delete boolean not null default false,
  primary key(role_key,page_key)
);

-- Profiles link Supabase Auth users to the legacy business identity and branch scope.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  email text,
  role_key text references public.roles(key),
  status text not null default 'Active',
  branch_id bigint references public.branches(id),
  profile_image text,
  theme_mode text default 'light',
  custom_colors jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_items_category on public.items(category_id);
create index if not exists idx_inventory_branch on public.inventory(branch_id);
create index if not exists idx_ledger_branch_item_date on public.stock_ledger(branch_id,item_id,movement_date);
create index if not exists idx_batches_expiry on public.batches(expiry_date);
create index if not exists idx_requests_branch_status on public.purchase_requests(branch_id,status);
create index if not exists idx_dispatches_to_branch on public.dispatches(to_branch_id);

insert into public.units(code,name,kind,base_code,factor,decimals) values
('GRM','Gram','weight','GRM',1,0),('KG','Kilogram','weight','GRM',1000,3),
('ML','Millilitre','volume','ML',1,0),('LTR','Litre','volume','ML',1000,3),
('GAL','Gallon','volume','ML',3785.41,3),('PCS','Piece','count','PCS',1,0),
('PKT','Packet','count','PCS',1,0),('BOX','Box','count','PCS',1,0),
('CTR','Carton','count','PCS',1,0),('ROLL','Roll','count','PCS',1,0)
on conflict(code) do nothing;

insert into public.roles(key,label,color,sort_order,is_super,hidden_signup) values
('Admin','Admin','#6a1b9a',0,true,true),
('StoreKeeper','Store Keeper','#0074D9',1,false,false),
('KitchenManager','Kitchen Manager','#e65100',2,false,false),
('BranchManager','Branch Manager','#2e7d32',3,false,false)
on conflict(key) do nothing;

-- RLS is enabled now; policies will be added with the authenticated application layer.
alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.role_permissions enable row level security;
alter table public.activity_logs enable row level security;
alter table public.branches enable row level security;
alter table public.categories enable row level security;
alter table public.vendors enable row level security;
alter table public.units enable row level security;
alter table public.items enable row level security;
alter table public.purchases enable row level security;
alter table public.purchase_items enable row level security;
alter table public.purchase_requests enable row level security;
alter table public.purchase_request_items enable row level security;
alter table public.productions enable row level security;
alter table public.production_materials enable row level security;
alter table public.dispatches enable row level security;
alter table public.dispatch_items enable row level security;
alter table public.inventory enable row level security;
alter table public.stock_ledger enable row level security;
alter table public.stock_adjustments enable row level security;
alter table public.par_levels enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_lines enable row level security;
alter table public.consumption enable row level security;
alter table public.consumption_lines enable row level security;
alter table public.stock_counts enable row level security;
alter table public.stock_count_lines enable row level security;
alter table public.batches enable row level security;
alter table public.vendor_items enable row level security;
